name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build--configuration Release
      run: dotnet build --configuration Release
      
    - name: Run tests
      run: dotnet test --configuration Release
    - name: dotnet publish
      run: dotnet publish
    - name: set up cdk
      run: rpm install
      
    - name: deployment.com
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.OMG_SECRETE }}
        port: 22
        script: |
          cd webApplication2
          git pull origin master
          git status
        
        
          

    
    
    
