name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    
    - name: SSH Server Deploy
      uses: kostya-ten/ssh-server-deploy@v4
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        scp_source: README.md
        scp_target: ~/
        before_script: |
          df -h
        after_script: |
          whoami
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build--configuration Release
      run: dotnet build --configuration Release
      
      
    - name: Run tests
      run: dotnet test --configuration Release
      
    - name: deployment.com
      uses: appleboy/ssh-action@master
      with:
        host: 68.183.36.52
        username: root
        key: ${{ secrets.OMG_SECRETE }}
        port: 22
        script: |
          cd webApplication2
          git pull origin master
          git status
          

    
    
    
