name: Release to Docker Hub

on:
  push:
    branches: master
    tags:
      - "*.*.*"
env:
   IMAGE_NAME: webApplication2

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
    
    - name: Login to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build and push Docker image
      id:   docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/webapplications:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
    - name: testing doosy-deploy ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOOSY_HOST }}
        username: root
        key: ${{ secrets.DOOSY_SECRET }}
        port: 22
        script: |
          docker pull kekgaugetswe/webapplications:latest
          docker create --name webapplications  -p 8083:80   kekgaugetswe/webapplications:latest
          docker ps -a
